### ISSUE TITLE
 CHANnel:DIAGnostics? still references input interlock

### ISSUE THREAD

**Issue by hartytp** [sinara-hw/Booster#284]
should this bit field just be labelled as `reserved (1)` or something?

**Comment by hartytp** [comment]
Sorry, these aren't bit fields so we should just delete that from the returned array and from the wiki...

**Comment by hartytp** [comment]
maybe better to just replace it with input power.

Can you also add fan speed while you're at it?

**Comment by wizath** [comment]
I would wait with removing input interlock signal till hardware will be removed. Just in case.

**Comment by hartytp** [comment]
Okay, fine, I'll just leave it out of my python driver and add a note on the wiki. Can we have the fan and input power measurements for completeness here please?

**Comment by wizath** [comment]
done

**Comment by hartytp** [comment]
thanks

**Comment by hartytp** [comment]
> done

fw please?

**Comment by wizath** [comment]
[eth-scpi.dfu.zip](https://github.com/sinara-hw/Booster/files/3601483/eth-scpi.dfu.zip)

**Comment by hartytp** [comment]
Nope, that build still doesn't (d52b929) seem to have the fan speed in `CHAN:DIAG?`
